source/malpo/config/routes.rb
Malpo::Application.routes.draw do
  resources :reports
  resources :technicians
  resources :malwares
  resources :mitigations
  resources :users
  resources :smashes
  resources :machines
  resources :companies
  resources :referents
  root 'malpo#index'

end

source/malpo/app/models/act.rb
class Act < ActiveRecord::Base
    has_many :includes
    has_many :mitigations, through: :includes
end

source/malpo/app/models/company.rb
class Company < ActiveRecord::Base
    belongs_to :referent
    has_many :machines
end

source/malpo/app/models/describe.rb
class Describe < ActiveRecord::Base
    belongs_to :report
    belongs_to :smash
end

source/malpo/app/models/has.rb
class Has < ActiveRecord::Base
    belongs_to :report
    belongs_to :mitigation
end

source/malpo/app/models/include.rb
class Include < ActiveRecord::Base
    belongs_to :act
    belongs_to :mitigation
end

source/malpo/app/models/machine.rb
class Machine < ActiveRecord::Base
    belongs_to :company
    has_many :reports
    has_many :uses
    has_many :users, through: :uses
end

source/malpo/app/models/malware.rb
class Malware < ActiveRecord::Base
    has_many :removals
    has_many :mitigation, through: :removals
    has_many :smashes
end

source/malpo/app/models/mitigation.rb
class Mitigation < ActiveRecord::Base
    has_many :has
    has_many :reports, through: :has
    has_many :includes
    has_many :acts, through: :includes
    has_many :removals
    has_many :malwares, through: :removals
end

source/malpo/app/models/position.rb
class Position < ActiveRecord::Base
    has_many :machines
end

source/malpo/app/models/referent.rb
class Referent < ActiveRecord::Base
    belongs_to :company
    has_many :reports
end

source/malpo/app/models/removal.rb
class Removal < ActiveRecord::Base
    belongs_to :mitigation
    belongs_to :malware
end

source/malpo/app/models/report.rb
class Report < ActiveRecord::Base
 validates :title, presence: true, length: { minimum: 5 }
 validates :score, presence: true
 validates :technician_id, presence: true
 validates :machine_id, presence: true
 validates :referent_id, presence: true
 belongs_to :technician
 belongs_to :referent
 belongs_to :machine
 has_many :users
 has_many :has
 has_many :mitigations, through: :has
 has_many :describes
 has_many :smashes, through: :describes
end

source/malpo/app/models/smash.rb
class Smash < ActiveRecord::Base
    belongs_to :malware
    has_many :describes
    has_many :reports, through: :describes
end

source/malpo/app/models/technician.rb
class Technician < ActiveRecord::Base
    has_many :reports
end

source/malpo/app/models/use.rb
class Use < ActiveRecord::Base
    belongs_to :user
    belongs_to :machine
end

source/malpo/app/models/user.rb
class User < ActiveRecord::Base
    belongs_to :report
    has_many :uses
    has_many :machines, through: :uses
end

source/malpo/app/controllers/companies_controller.rb
class CompanisController < ApplicationController
    def new
        @company = Company.new
    end

    def create
        @company = Company.new(company_params)
        if @company.save
            redirect_to @company
        else
            render 'new'
        end
    end

    def show
        @company = Company.find(params[:id])
    end

    def index
        @companies = Company.all
    end

    def edit
        @company = Company.find(params[:id])
    end

    def update
        @company = Company.find(params[:id])

        if @company.update(company_params)
            redirect_to @company
        else
            render 'edit'
        end
    end

    def destroy
        @company = Company.find(params[:id])
        @company.destroy

        redirect_to companies_path
    end

    # Strong parameters
    private
    def company_params
        params.require(:company).permit()
    end
end

source/malpo/app/helpers/application_helper.rb
module ApplicationHelper
end

source/malpo/app/helpers/malpo_helper.rb
module MalpoHelper
end

source/malpo/app/helpers/referents_helper.rb
module ReferentsHelper
end

source/malpo/app/helpers/reports_helper.rb
module ReportsHelper
end

source/malpo/app/helpers/users_helper.rb
module UsersHelper
end

source/malpo/app/views/companies/_form.html.erb
<%= form_for @company, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :rs, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :rs, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :web, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :web, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :referent_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :referent_id, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                companies_path, :class => 'btn' %>
  </div>
<% end %>

source/malpo/app/views/companies/edit.html.erb
<%- model_class = Company -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

source/malpo/app/views/companies/index.html.erb
<%- model_class = Company -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:rs) %></th>
      <th><%= model_class.human_attribute_name(:web) %></th>
      <th><%= model_class.human_attribute_name(:referent_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= link_to company.id, company_path(company) %></td>
        <td><%= company.name %></td>
        <td><%= company.rs %></td>
        <td><%= company.web %></td>
        <td><%= company.referent_id %></td>
        <td><%=l company.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_company_path(company), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      company_path(company),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_company_path,
            :class => 'btn btn-primary' %>

source/malpo/app/views/companies/new.html.erb
<%- model_class = Company -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

source/malpo/app/views/companies/show.html.erb
<%- model_class = Company -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @company.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:rs) %>:</strong></dt>
  <dd><%= @company.rs %></dd>
  <dt><strong><%= model_class.human_attribute_name(:web) %>:</strong></dt>
  <dd><%= @company.web %></dd>
  <dt><strong><%= model_class.human_attribute_name(:referent_id) %>:</strong></dt>
  <dd><%= @company.referent_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              companies_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_company_path(@company), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              company_path(@company),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>