source/malpo/config/routes.rb
Malpo::Application.routes.draw do
  resources :reports
  resources :technicians
  resources :malwares
  resources :mitigations
  resources :users
  resources :smashes
  resources :machines
  resources :companies
  resources :referents
  root 'malpo#index'

end

source/malpo/app/models/act.rb
class Act < ActiveRecord::Base
    has_many :includes
    has_many :mitigations, through: :includes
end

source/malpo/app/models/company.rb
class Company < ActiveRecord::Base
    belongs_to :referent
    has_many :machines
end

source/malpo/app/models/describe.rb
class Describe < ActiveRecord::Base
    belongs_to :report
    belongs_to :smash
end

source/malpo/app/models/has.rb
class Has < ActiveRecord::Base
    belongs_to :report
    belongs_to :mitigation
end

source/malpo/app/models/include.rb
class Include < ActiveRecord::Base
    belongs_to :act
    belongs_to :mitigation
end

source/malpo/app/models/machine.rb
class Machine < ActiveRecord::Base
    belongs_to :company
    has_many :reports
    has_many :uses
    has_many :users, through: :uses
end

source/malpo/app/models/malware.rb
class Malware < ActiveRecord::Base
    has_many :removals
    has_many :mitigation, through: :removals
    has_many :smashes
end

source/malpo/app/models/mitigation.rb
class Mitigation < ActiveRecord::Base
    has_many :has
    has_many :reports, through: :has
    has_many :includes
    has_many :acts, through: :includes
    has_many :removals
    has_many :malwares, through: :removals
end

source/malpo/app/models/position.rb
class Position < ActiveRecord::Base
    has_many :machines
end

source/malpo/app/models/referent.rb
class Referent < ActiveRecord::Base
    belongs_to :company
    has_many :reports
end

source/malpo/app/models/removal.rb
class Removal < ActiveRecord::Base
    belongs_to :mitigation
    belongs_to :malware
end

source/malpo/app/models/report.rb
class Report < ActiveRecord::Base
 validates :title, presence: true, length: { minimum: 5 }
 validates :score, presence: true
 validates :technician_id, presence: true
 validates :machine_id, presence: true
 validates :referent_id, presence: true
 belongs_to :technician
 belongs_to :referent
 belongs_to :machine
 has_many :users
 has_many :has
 has_many :mitigations, through: :has
 has_many :describes
 has_many :smashes, through: :describes
end

source/malpo/app/models/smash.rb
class Smash < ActiveRecord::Base
    belongs_to :malware
    has_many :describes
    has_many :reports, through: :describes
end

source/malpo/app/models/technician.rb
class Technician < ActiveRecord::Base
    has_many :reports
end

source/malpo/app/models/use.rb
class Use < ActiveRecord::Base
    belongs_to :user
    belongs_to :machine
end

source/malpo/app/models/user.rb
class User < ActiveRecord::Base
    belongs_to :report
    has_many :uses
    has_many :machines, through: :uses
end

source/malpo/app/controllers/malwares_controller.rb
class MalwaresController < ApplicationController
    def new
        @malware = Malware.new
    end

    def create
        @malware = Malware.new(malware_params)
        if @malware.save
            redirect_to @malware
        else
            render 'new'
        end
    end

    def show
        @malware = Malware.find(params[:id])
    end

    def index
        @malwares = Malware.all
    end

    def edit
        @malware = Malware.find(params[:id])
    end

    def update
        @malware = Malware.find(params[:id])

        if @malware.update(malware_params)
            redirect_to @malware
        else
            render 'edit'
        end
    end

    def destroy
        @malware = Malware.find(params[:id])
        @malware.destroy

        redirect_to malwares_path
    end

    # Strong parameters
    private
    def malware_params
        params.require(:malware).permit()
    end
end

source/malpo/app/helpers/application_helper.rb
module ApplicationHelper
end

source/malpo/app/helpers/malpo_helper.rb
module MalpoHelper
end

source/malpo/app/helpers/referents_helper.rb
module ReferentsHelper
end

source/malpo/app/helpers/reports_helper.rb
module ReportsHelper
end

source/malpo/app/helpers/users_helper.rb
module UsersHelper
end

source/malpo/app/views/malwares/_form.html.erb
<%= form_for @malware, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :family, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :family, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :version, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :version, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                malwares_path, :class => 'btn' %>
  </div>
<% end %>

source/malpo/app/views/malwares/edit.html.erb
<%- model_class = Malware -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

source/malpo/app/views/malwares/index.html.erb
<%- model_class = Malware -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:family) %></th>
      <th><%= model_class.human_attribute_name(:version) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @malwares.each do |malware| %>
      <tr>
        <td><%= link_to malware.id, malware_path(malware) %></td>
        <td><%= malware.family %></td>
        <td><%= malware.version %></td>
        <td><%= malware.description %></td>
        <td><%=l malware.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_malware_path(malware), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      malware_path(malware),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_malware_path,
            :class => 'btn btn-primary' %>

source/malpo/app/views/malwares/new.html.erb
<%- model_class = Malware -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

source/malpo/app/views/malwares/show.html.erb
<%- model_class = Malware -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:family) %>:</strong></dt>
  <dd><%= @malware.family %></dd>
  <dt><strong><%= model_class.human_attribute_name(:version) %>:</strong></dt>
  <dd><%= @malware.version %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @malware.description %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              malwares_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_malware_path(@malware), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              malware_path(@malware),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>