source/malpo/config/routes.rb
Malpo::Application.routes.draw do
  resources :reports
  resources :technicians
  resources :malwares
  resources :mitigations
  resources :users
  resources :smashes
  resources :machines
  resources :companies
  resources :referents
  root 'malpo#index'

end

source/malpo/app/models/act.rb
class Act < ActiveRecord::Base
    has_many :includes
    has_many :mitigations, through: :includes
end

source/malpo/app/models/company.rb
class Company < ActiveRecord::Base
    belongs_to :referent
    has_many :machines
end

source/malpo/app/models/describe.rb
class Describe < ActiveRecord::Base
    belongs_to :report
    belongs_to :smash
end

source/malpo/app/models/has.rb
class Has < ActiveRecord::Base
    belongs_to :report
    belongs_to :mitigation
end

source/malpo/app/models/include.rb
class Include < ActiveRecord::Base
    belongs_to :act
    belongs_to :mitigation
end

source/malpo/app/models/machine.rb
class Machine < ActiveRecord::Base
    belongs_to :company
    has_many :reports
    has_many :uses
    has_many :users, through: :uses
end

source/malpo/app/models/malware.rb
class Malware < ActiveRecord::Base
    has_many :removals
    has_many :mitigation, through: :removals
    has_many :smashes
end

source/malpo/app/models/mitigation.rb
class Mitigation < ActiveRecord::Base
    has_many :has
    has_many :reports, through: :has
    has_many :includes
    has_many :acts, through: :includes
    has_many :removals
    has_many :malwares, through: :removals
end

source/malpo/app/models/position.rb
class Position < ActiveRecord::Base
    has_many :machines
end

source/malpo/app/models/referent.rb
class Referent < ActiveRecord::Base
    belongs_to :company
    has_many :reports
end

source/malpo/app/models/removal.rb
class Removal < ActiveRecord::Base
    belongs_to :mitigation
    belongs_to :malware
end

source/malpo/app/models/report.rb
class Report < ActiveRecord::Base
 validates :title, presence: true, length: { minimum: 5 }
 validates :score, presence: true
 validates :technician_id, presence: true
 validates :machine_id, presence: true
 validates :referent_id, presence: true
 belongs_to :technician
 belongs_to :referent
 belongs_to :machine
 has_many :users
 has_many :has
 has_many :mitigations, through: :has
 has_many :describes
 has_many :smashes, through: :describes
end

source/malpo/app/models/smash.rb
class Smash < ActiveRecord::Base
    belongs_to :malware
    has_many :describes
    has_many :reports, through: :describes
end

source/malpo/app/models/technician.rb
class Technician < ActiveRecord::Base
    has_many :reports
end

source/malpo/app/models/use.rb
class Use < ActiveRecord::Base
    belongs_to :user
    belongs_to :machine
end

source/malpo/app/models/user.rb
class User < ActiveRecord::Base
    belongs_to :report
    has_many :uses
    has_many :machines, through: :uses
end

source/malpo/app/controllers/machines_controller.rb
class MachinesController < ApplicationController
    def new
        @machine = Machine.new
    end

    def create
        @machine = Machine.new(machine_params)
        if @machine.save
            redirect_to @machine
        else
            render 'new'
        end
    end

    def show
        @machine = Machine.find(params[:id])
    end

    def index
        @machines = Machine.all
    end

    def edit
        @machine = Machine.find(params[:id])
    end

    def update
        @machine = Machine.find(params[:id])

        if @machine.update(machine_params)
            redirect_to @machine
        else
            render 'edit'
        end
    end

    def destroy
        @machine = Machine.find(params[:id])
        @machine.destroy

        redirect_to machines_path
    end

    # Strong parameters
    private
    def machine_params
        params.require(:machine).permit()
    end
end

source/malpo/app/helpers/application_helper.rb
module ApplicationHelper
end

source/malpo/app/helpers/malpo_helper.rb
module MalpoHelper
end

source/malpo/app/helpers/referents_helper.rb
module ReferentsHelper
end

source/malpo/app/helpers/reports_helper.rb
module ReportsHelper
end

source/malpo/app/helpers/users_helper.rb
module UsersHelper
end

source/malpo/app/views/machines/_form.html.erb
<%= form_for @machine, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :hostname, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :hostname, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :os, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :os, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :version, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :version, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :type, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :type, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :role, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :role, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :ip, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :ip, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :latitude, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :latitude, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :longitude, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :longitude, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :city, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :city, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :state, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :state, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :company_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :company_id, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                machines_path, :class => 'btn' %>
  </div>
<% end %>

source/malpo/app/views/machines/edit.html.erb
<%- model_class = Machine -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

source/malpo/app/views/machines/index.html.erb
<%- model_class = Machine -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:hostname) %></th>
      <th><%= model_class.human_attribute_name(:os) %></th>
      <th><%= model_class.human_attribute_name(:version) %></th>
      <th><%= model_class.human_attribute_name(:type) %></th>
      <th><%= model_class.human_attribute_name(:role) %></th>
      <th><%= model_class.human_attribute_name(:ip) %></th>
      <th><%= model_class.human_attribute_name(:latitude) %></th>
      <th><%= model_class.human_attribute_name(:longitude) %></th>
      <th><%= model_class.human_attribute_name(:city) %></th>
      <th><%= model_class.human_attribute_name(:state) %></th>
      <th><%= model_class.human_attribute_name(:company_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @machines.each do |machine| %>
      <tr>
        <td><%= link_to machine.id, machine_path(machine) %></td>
        <td><%= machine.hostname %></td>
        <td><%= machine.os %></td>
        <td><%= machine.version %></td>
        <td><%= machine.type %></td>
        <td><%= machine.role %></td>
        <td><%= machine.ip %></td>
        <td><%= machine.latitude %></td>
        <td><%= machine.longitude %></td>
        <td><%= machine.city %></td>
        <td><%= machine.state %></td>
        <td><%= machine.company_id %></td>
        <td><%=l machine.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_machine_path(machine), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      machine_path(machine),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_machine_path,
            :class => 'btn btn-primary' %>

source/malpo/app/views/machines/new.html.erb
<%- model_class = Machine -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

source/malpo/app/views/machines/show.html.erb
<%- model_class = Machine -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:hostname) %>:</strong></dt>
  <dd><%= @machine.hostname %></dd>
  <dt><strong><%= model_class.human_attribute_name(:os) %>:</strong></dt>
  <dd><%= @machine.os %></dd>
  <dt><strong><%= model_class.human_attribute_name(:version) %>:</strong></dt>
  <dd><%= @machine.version %></dd>
  <dt><strong><%= model_class.human_attribute_name(:type) %>:</strong></dt>
  <dd><%= @machine.type %></dd>
  <dt><strong><%= model_class.human_attribute_name(:role) %>:</strong></dt>
  <dd><%= @machine.role %></dd>
  <dt><strong><%= model_class.human_attribute_name(:ip) %>:</strong></dt>
  <dd><%= @machine.ip %></dd>
  <dt><strong><%= model_class.human_attribute_name(:latitude) %>:</strong></dt>
  <dd><%= @machine.latitude %></dd>
  <dt><strong><%= model_class.human_attribute_name(:longitude) %>:</strong></dt>
  <dd><%= @machine.longitude %></dd>
  <dt><strong><%= model_class.human_attribute_name(:city) %>:</strong></dt>
  <dd><%= @machine.city %></dd>
  <dt><strong><%= model_class.human_attribute_name(:state) %>:</strong></dt>
  <dd><%= @machine.state %></dd>
  <dt><strong><%= model_class.human_attribute_name(:company_id) %>:</strong></dt>
  <dd><%= @machine.company_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              machines_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_machine_path(@machine), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              machine_path(@machine),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>