source/malpo/config/routes.rb
Malpo::Application.routes.draw do
  resources :reports
  resources :technicians
  resources :malwares
  resources :mitigations
  resources :users
  resources :smashes
  resources :machines
  resources :companies
  resources :referents
  root 'malpo#index'

end

source/malpo/app/models/act.rb
class Act < ActiveRecord::Base
    has_many :includes
    has_many :mitigations, through: :includes
end

source/malpo/app/models/company.rb
class Company < ActiveRecord::Base
    belongs_to :referent
    has_many :machines
end

source/malpo/app/models/describe.rb
class Describe < ActiveRecord::Base
    belongs_to :report
    belongs_to :smash
end

source/malpo/app/models/has.rb
class Has < ActiveRecord::Base
    belongs_to :report
    belongs_to :mitigation
end

source/malpo/app/models/include.rb
class Include < ActiveRecord::Base
    belongs_to :act
    belongs_to :mitigation
end

source/malpo/app/models/machine.rb
class Machine < ActiveRecord::Base
    belongs_to :company
    has_many :reports
    has_many :uses
    has_many :users, through: :uses
end

source/malpo/app/models/malware.rb
class Malware < ActiveRecord::Base
    has_many :removals
    has_many :mitigation, through: :removals
    has_many :smashes
end

source/malpo/app/models/mitigation.rb
class Mitigation < ActiveRecord::Base
    has_many :has
    has_many :reports, through: :has
    has_many :includes
    has_many :acts, through: :includes
    has_many :removals
    has_many :malwares, through: :removals
end

source/malpo/app/models/position.rb
class Position < ActiveRecord::Base
    has_many :machines
end

source/malpo/app/models/referent.rb
class Referent < ActiveRecord::Base
    belongs_to :company
    has_many :reports
end

source/malpo/app/models/removal.rb
class Removal < ActiveRecord::Base
    belongs_to :mitigation
    belongs_to :malware
end

source/malpo/app/models/report.rb
class Report < ActiveRecord::Base
 validates :title, presence: true, length: { minimum: 5 }
 validates :score, presence: true
 validates :technician_id, presence: true
 validates :machine_id, presence: true
 validates :referent_id, presence: true
 belongs_to :technician
 belongs_to :referent
 belongs_to :machine
 has_many :users
 has_many :has
 has_many :mitigations, through: :has
 has_many :describes
 has_many :smashes, through: :describes
end

source/malpo/app/models/smash.rb
class Smash < ActiveRecord::Base
    belongs_to :malware
    has_many :describes
    has_many :reports, through: :describes
end

source/malpo/app/models/technician.rb
class Technician < ActiveRecord::Base
    has_many :reports
end

source/malpo/app/models/use.rb
class Use < ActiveRecord::Base
    belongs_to :user
    belongs_to :machine
end

source/malpo/app/models/user.rb
class User < ActiveRecord::Base
    belongs_to :report
    has_many :uses
    has_many :machines, through: :uses
end

source/malpo/app/controllers/referents_controller.rb
class ReferentsController < ApplicationController
    def new
        @referent = Referent.new
    end

    def create
        @referent = Referent.new(referent_params)
        if @referent.save
            redirect_to @referent
        else
            render 'new'
        end
    end

    def show
        @referent = Referent.find(params[:id])
    end

    def index
        @referents = Referent.all
    end

    def edit
        @referent = Referent.find(params[:id])
    end

    def update
        @referent = Referent.find(params[:id])

        if @referent.update(referent_params)
            redirect_to @referent
        else
            render 'edit'
        end
    end

    def destroy
        @referent = Referent.find(params[:id])
        @referent.destroy

        redirect_to referents_path
    end

    # Strong parameters
    private
    def referent_params
        params.require(:post).permit(:name, :surname, :via, :civico, :comune, :cap, :email, :idcompany)
    end
end

source/malpo/app/helpers/application_helper.rb
module ApplicationHelper
end

source/malpo/app/helpers/malpo_helper.rb
module MalpoHelper
end

source/malpo/app/helpers/referents_helper.rb
module ReferentsHelper
end

source/malpo/app/helpers/reports_helper.rb
module ReportsHelper
end

source/malpo/app/helpers/technicians_helper.rb
module TechniciansHelper
end

source/malpo/app/helpers/users_helper.rb
module UsersHelper
end

source/malpo/app/views/referents/_form.html.erb
<%= form_for @technician do |f| %>
    <% if @technician.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@technician.errors.count, "error") %> prohibited
                this technician from being saved:</h2>
            <ul>
                <% @technician.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <p>
    <%= f.label :name %><br>
    <%= f.date_field :name %>
    </p>
    <p>
    <%= f.label :surname %><br>
    <%= f.text_field :surname %>
    </p>
    <p>
    <%= f.label :via %><br>
    <%= f.text_field :via %>
    </p>
    <p>
    <%= f.label :civico %><br>
    <%= f.text_field :civico %>
    </p>
    <p>
    <%= f.label :comune %><br>
    <%= f.text_field :comune %>
    </p>
    <p>
    <%= f.label :cap %><br>
    <%= f.text_field :cap %>
    </p>
    <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
    </p>

    <p>
    <%= f.submit %>
    </p>
<% end %>

source/malpo/app/views/referents/edit.html.erb
<h1>edit a technician</h1>
<%= render 'form' %>
<%= link_to "Back", technicians_path %>

source/malpo/app/views/referents/index.html.erb
<h1>Listing technicians</h1>

<%= link_to "New technician", new_technician_path %>
<table>
    <tr>
        <th>IdTechnician</th>
        <th>Name</th>
        <th>Surname</th>
        <th>Via</th>
        <th>Civico</th>
        <th>Comune</th>
        <th>Cap</th>
        <th>Email</th>
        <th>IdReferent</th>
    </tr>

    <% @technicians.each do |technician| %>
        <tr>
            <td><%= technician.id %></td>
            <td><%= technician.name %></td>
            <td><%= technician.surname %></td>
            <td><%= technician.via %></td>
            <td><%= technician.civico %></td>
            <td><%= technician.comune %></td>
            <td><%= technician.cap %></td>
            <td><%= technician.email %></td>
            <td><%= technician.idref %></td>
            <td><%= link_to 'Show', technician %></td>
            <td><%= link_to 'Edit', { action: :edit, id: technician.id } %></td>
            <td><%= link_to 'Destroy', { action: :destroy, id: technician.id },
                method: :delete, data: { confirm: 'Are you REALLY sure?' } %></td>
        </tr>
    <% end %>
</table>

source/malpo/app/views/referents/new.html.erb
<h1>making a technician</h1>
<%= render 'form' %>
<%= link_to "Back", technicians_path %>

source/malpo/app/views/referents/show.html.erb
<p>
  <strong>IdTechnician:</strong>
  <%= @technician.id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @technician.name %>
</p>

<p>
  <strong>Surname:</strong>
  <%= @technician.surname %>
</p>

<p>
  <strong>Via:</strong>
  <%= @technician.via %>
</p>

<p>
  <strong>Civico:</strong>
  <%= @technician.civico %>
</p>

<p>
  <strong>Comune:</strong>
  <%= @technician.comune %>
</p>

<p>
  <strong>Cap:</strong>
  <%= @technician.cap %>
</p>

<p>
  <strong>Email:</strong>
  <%= @technician.email %>
</p>

%= link_to "Back", technicians_path %> | <%= link_to "Edit", edit_technician_path(@technician)>